### ISSUE TITLE
Problem running extractor from o2r-loader

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#59]
After updating to the latest meta tools, like this

`python3 ../o2r-meta/o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/LnnDN/data --outputdir /tmp/o2r/compendium/LnnDN/data/.erc --metafiles --ercid LnnDN --basedir /tmp/o2r/compendium/ --stayoffline`

<details>
<summary>error log (with some debug statements added)</summary>

```
  loader [1tdmH] Extracting metadata +1ms
  loader [1tdmH] Running metadata extraction with command "python3 ../o2r-meta/o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/1tdmH/data --outputdir /tmp/o2r/compendium/1tdmH/data/.erc --metafiles --ercid 1tdmH --basedir /tmp/o2r/compendium/ --stayoffline" +0ms
  loader [1tdmH] Problem during metadata extraction:    Command failed: python3 ../o2r-meta/o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/1tdmH/data --outputdir /tmp/o2r/compendium/1tdmH/data/.erc --metafiles --ercid 1tdmH --basedir /tmp/o2r/compendium/ --stayoffline
Traceback (most recent call last):
  File "../o2r-meta/o2rmeta.py", line 78, in <module>
    metaextract.start(dbg=argsd['debug'], i=argsd['inputdir'], o=argsd['outputdir'], s=argsd['outputtostdout'], xo=argsd['stayoffline'], e=argsd['ercid'], f=argsd['formats'], b=argsd['basedir'], m=argsd['metafiles'], xml=argsd['modexml'])
  File "/home/daniel/git/o2r/o2r-meta/extract/metaextract.py", line 336, in start
    with open(os.path.join("..", "schema", "json", "dummy.json"), 'w', encoding='utf-8') as dummyfile:
FileNotFoundError: [Errno 2] No such file or directory: '../schema/json/dummy.json'

  loader        Traceback (most recent call last):
  File "../o2r-meta/o2rmeta.py", line 78, in <module>
    metaextract.start(dbg=argsd['debug'], i=argsd['inputdir'], o=argsd['outputdir'], s=argsd['outputtostdout'], xo=argsd['stayoffline'], e=argsd['ercid'], f=argsd['formats'], b=argsd['basedir'], m=argsd['metafiles'], xml=argsd['modexml'])
  File "/home/daniel/git/o2r/o2r-meta/extract/metaextract.py", line 336, in start
    with open(os.path.join("..", "schema", "json", "dummy.json"), 'w', encoding='utf-8') as dummyfile:
FileNotFoundError: [Errno 2] No such file or directory: '../schema/json/dummy.json'
 +485ms
  loader Error: Command failed: python3 ../o2r-meta/o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/1tdmH/data --outputdir /tmp/o2r/compendium/1tdmH/data/.erc --metafiles --ercid 1tdmH --basedir /tmp/o2r/compendium/ --stayoffline
  loader Traceback (most recent call last):
  loader   File "../o2r-meta/o2rmeta.py", line 78, in <module>
  loader     metaextract.start(dbg=argsd['debug'], i=argsd['inputdir'], o=argsd['outputdir'], s=argsd['outputtostdout'], xo=argsd['stayoffline'], e=argsd['ercid'], f=argsd['formats'], b=argsd['basedir'], m=argsd['metafiles'], xml=argsd['modexml'])
  loader   File "/home/daniel/git/o2r/o2r-meta/extract/metaextract.py", line 336, in start
  loader     with open(os.path.join("..", "schema", "json", "dummy.json"), 'w', encoding='utf-8') as dummyfile:
  loader FileNotFoundError: [Errno 2] No such file or directory: '../schema/json/dummy.json'
  loader
  loader     at ChildProcess.exithandler (child_process.js:270:12)
  loader     at emitTwo (events.js:125:13)
  loader     at ChildProcess.emit (events.js:213:7)
  loader     at maybeClose (internal/child_process.js:927:16)
  loader     at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:211:5) Traceback (most recent call last):
  File "../o2r-meta/o2rmeta.py", line 78, in <module>
    metaextract.start(dbg=argsd['debug'], i=argsd['inputdir'], o=argsd['outputdir'], s=argsd['outputtostdout'], xo=argsd['stayoffline'], e=argsd['ercid'], f=argsd['formats'], b=argsd['basedir'], m=argsd['metafiles'], xml=argsd['modexml'])
  File "/home/daniel/git/o2r/o2r-meta/extract/metaextract.py", line 336, in start
    with open(os.path.join("..", "schema", "json", "dummy.json"), 'w', encoding='utf-8') as dummyfile:
FileNotFoundError: [Errno 2] No such file or directory: '../schema/json/dummy.json'
 [o2rmeta] 20171020.175315 received arguments: {'inputdir': '/tmp/o2r/compendium/1tdmH/data', 'outputtostdout': False, 'modexml': False, 'ercid': '1tdmH', 'debug': True, 'basedir': '/tmp/o2r/compendium/', 'stayoffline': True, 'tool': 'extract', 'metafiles': True, 'outputdir': '/tmp/o2r/compendium/1tdmH/data/.erc', 'formats': False}
[o2rmeta] 20171020.175315 launching extractor
[o2rmeta] 20171020.175315 directory </tmp/o2r/compendium/1tdmH/data/.erc> will be created during extraction...
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171020.175315 <parsers.parse_bagittxt.ParseBagitTxt object at 0x7ff3838eafd0>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171020.175315 <parsers.parse_displayfiles.ParseDisplayFiles object at 0x7ff3838f10b8>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171020.175315 <parsers.parse_geojson.ParseGeojson object at 0x7ff3838f1128>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171020.175315 <parsers.parse_rmd.ParseRmd object at 0x7ff3838f1390>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171020.175315 <parsers.parse_rdata.ParseRData object at 0x7ff3838f1400>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171020.175315 <parsers.parse_yaml.ParseYaml object at 0x7ff3838f1978>
[o2rmeta][debug: extract.metaextract @ start] 20171020.175315 i think i am at /home/daniel/git/o2r/o2r-meta/extract/metaextract.py
[o2rmeta][debug: extract.metaextract @ start] 20171020.175315 current cwd: /home/daniel/git/o2r/o2r-loader
 +1ms
  loader:directuploader [1tdmH] Rejection or unhandled failure during upload:
  loader:directuploader         {"killed":false,"code":1,"signal":null,"cmd":"python3 ../o2r-meta/o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/1tdmH/data --outputdir /tmp/o2r/compendium/1tdmH/data/.erc --metafiles --ercid 1tdmH --basedir /tmp/o2r/compendium/ --stayoffline","msg":"metadata extraction failed: '../schema/json/dummy.json'"}
```
</details>

I think this is an issue with [resolving the relative file path](https://github.com/o2r-project/o2r-meta/blob/448e4cceaa4d266578e1b0eeae42e0baa6ec0653/extract/metaextract.py#L334).

`os.getcwd()` just before that line returns `/home/daniel/git/o2r/o2r-loader`, which in my case is the directory of the loader, i.e. the directory of the Node.js process calling o2r-meta.

The following change worked for me, but also changed the dummy file (!):

```diff
diff --git a/extract/metaextract.py b/extract/metaextract.py
index bb8550d..b52cdc4 100644
--- a/extract/metaextract.py
+++ b/extract/metaextract.py
@@ -331,7 +331,8 @@ def start(**kwargs):
     global file_list_input_candidates
     # create dummy file to indicate latest data structure
     try:
-        with open(os.path.join("schema", "json", "dummy.json"), 'w', encoding='utf-8') as dummyfile:
+        status_note(['Using dummy schema file from ', dummy_file_path], d=is_debug)
+        with open(dummy_file_path, 'w', encoding='utf-8') as dummyfile:
             dummyfile.write(json.dumps(MASTER_MD_DICT, sort_keys=True, indent=4, separators=(',', ': ')))
     except Exception as exc:
         if is_debug:
diff --git a/schema/json/dummy.json b/schema/json/dummy.json
index e50979e..776db2c 100644
--- a/schema/json/dummy.json
+++ b/schema/json/dummy.json
@@ -14,7 +14,7 @@
     "description": null,
     "displayfile": null,
     "displayfile_candidates": [],
-    "ercIdentifier": null,
+    "ercIdentifier": "bsWlK",
     "file": {
         "filename": null,
         "filepath": null,
```

This leads me to believe that writing the dummyfile should _not_ happen during every extract...

**Comment by 7048730** [comment]
when switching to modular parses I removed the function for relative paths because I thought it was useless, that's why its gone. I can fix that.
the dummyfile is written in every run on purpose so I can provide a current dummyfile while making changes to the elements without forgetting it. jan asked for this

**Comment by 7048730** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '../schema/json/dummy.json'

upon examination, I am very suprised about this error since this is old code and never made problems before. did you change the setup? also, I cannot reproduce the error on my machine

**Comment by nuest** [comment]
Reproducible example based on current `dev` branch:

**Running o2rmeta.py directly:**

```
~/git/o2r/o2r-meta$ python3 o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/G4St5/data --outputdir /tmp/test-1 --metafiles --ercid test --basedir /tmp/o2r/compendium/--stayoffline
[o2rmeta] 20171024.100105 received arguments: {'ercid': 'test', 'metafiles': True, 'inputdir': '/tmp/o2r/compendium/G4St5/data', 'stayoffline': True, 'outputtostdout': False, 'formats': False,'basedir': '/tmp/o2r/compendium/', 'tool': 'extract', 'debug': True, 'outputdir': '/tmp/test-1', 'modexml': False}
[o2rmeta] 20171024.100105 launching extractor
[o2rmeta] 20171024.100105 directory </tmp/test-1> will be created during extraction...
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100105 <parsers.parse_bagittxt.ParseBagitTxt object at 0x7f2264705f28>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100105 <parsers.parse_displayfiles.ParseDisplayFiles object at 0x7f2264705cf8>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100105 <parsers.parse_geojson.ParseGeojson object at 0x7f2264705e48>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100105 <parsers.parse_rmd.ParseRmd object at 0x7f22647055f8>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100105 <parsers.parse_rdata.ParseRData object at 0x7f2264705518>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100105 <parsers.parse_yaml.ParseYaml object at 0x7f226470a0b8>
[o2rmeta] 20171024.100105 skipping orcid lookup (http disabled)
[o2rmeta] 20171024.100105 skipping orcid lookup (http disabled)
[o2rmeta][debug: extract.metaextract @ start] 20171024.100105 /tmp/o2r/compendium/G4St5/data/document.Rmd
[o2rmeta][debug: extract.metaextract @ start] 20171024.100105 /tmp/o2r/compendium/G4St5/data/document.html
[o2rmeta] 20171024.100105 5 files processed
{'interaction': {'interactive': False, 'ui_binding': {'variable': None, 'widget': None, 'purpose': None, 'code': {'shinyRenderFunction': None, 'shinyInputFunction': None, 'function': None, 'filename': None, 'functionParameter': None}}}, 'recordDateCreated': None, 'paperLanguage': [], 'description': 'Tempus eget nunc eu, lobortis condimentum nulla. Nam sagittis massa nec libero luctus facilisis. Suspendisse ac ornare ligula. Morbi non dignissim sem. Pellentesque eleifend neque nec dui interdum varius.\n', 'depends': [{'category': 'geo sciences,CRAN Top100', 'packageSystem': 'https://cloud.r-project.org/', 'identifier': 'RColorBrewer', 'version': None}, {'category': 'geo sciences,CRAN Top100', 'packageSystem': 'https://cloud.r-project.org/', 'identifier': 'dplyr', 'version': None}, {'category': 'geo sciences,CRAN Top100', 'packageSystem': 'https://cloud.r-project.org/', 'identifier': 'ggplot2', 'version': None}, {'category': 'CRAN Top100', 'packageSystem': 'https://cloud.r-project.org/', 'identifier': 'minqa', 'version': None}, {'category': 'geo sciences', 'packageSystem': 'https://cloud.r-project.org/', 'identifier': 'PBSmapping', 'version': None}], 'researchHypotheses': [], 'displayfile': None, 'r_comment': [{'line': 9, 'text': 'Trying some seperation lines:', 'feature': 'comment'}, {'line': 13, 'text': 'chunk: random string', 'feature': 'comment'}, {'line': 18, 'text': 'umlaut ö ä ü ß', 'feature': 'comment'}, {'line': 22, 'text': 'some plot', 'feature': 'comment'}], 'displayfile_candidates': ['/tmp/o2r/compendium/G4St5/data/document.html'], 'r_rdata': [], 'provenance': {'/tmp/o2r/compendium/G4St5/data/document.Rmd': 'parsers.parse_rmd parse'}, 'publicationDate': None, 'softwarePaperCitation': None, 'spatial': {'union': None, 'files': []}, 'title': 'This is the title: it contains a colon', 'mainfile_candidates': ['/tmp/o2r/compendium/G4St5/data/document.Rmd'], 'communities': [{'identifier': 'o2r'}], 'file': {'filepath': None, 'filename': None, 'mimetype': None}, 'r_output': [{'line': 14, 'text': '42', 'feature': 'setseed'}, {'line': 23, 'text': 'plot', 'feature': 'result'}, {'line': 25, 'text': 'print', 'feature': 'result'}], 'inputfiles': [], 'license': {'text': None, 'data': None, 'code': None, 'md': None, 'uibindings': None}, 'ercIdentifier': 'test', 'access_right': 'open', 'r_input': [], 'bagit': {'bagittxt_files': []}, 'researchQuestions': [], 'keywords': ['lorem', 'ipsum', 'dolor', 'sit', 'amet'], 'mainfile': '/tmp/o2r/compendium/G4St5/data/document.Rmd', 'upload_type': 'publication', 'temporal': {'end': None, 'begin': None}, 'identifier': {'doi': None, 'doiurl': None, 'reserveddoi': None}, 'version': None, 'publication_type': 'other', 'codefiles': ['/tmp/o2r/compendium/G4St5/data/document.Rmd'], 'author': [{'orcid': None, 'url': '\\url{http://404.awebsite8372930.org}', 'address': 'This might be a correct address Yet it might also be lorem ipsum\\newline Another line 252b\\newline 00000 Anywhere, Nomansland\n', 'name': 'Ted Tester', 'affiliation2': 'University of Nowhere', 'email': 'ted.tester@awebsite8372930.org', 'affiliation': 'University of Munster', 'Telephone': '+00/00/1000-2000'}, {'orcid': None, 'affiliation': 'N.O.N.E', 'name': 'Carl Connauthora'}], 'generatedBy': 'o2r-meta metaextract.py', 'paperSource': None}
[o2rmeta] 20171024.100105 5287 bytes written to ../../../../../tmp/test-1/metadata_raw.json
[o2rmeta] 20171024.100105 skipping erc spec download (http disabled)
~/git/o2r/o2r-meta$ ls /tmp/test-1/
metadata_raw.json
```

**Running o2rmeta from another directory:**

```
$ cd /tmp/o2r/
/tmp/o2r$ python3 ~/git/o2r/o2r-meta/o2rmeta.py -debug extract --inputdir /tmp/o2r/compendium/G4St5/data --outputdir /tmp/test-2 --metafiles --ercid test --basedir /tmp/o2r/compendium/ --stayoffline
[o2rmeta] 20171024.100225 received arguments: {'tool': 'extract', 'formats': False, 'modexml': False, 'stayoffline': True, 'debug': True, 'outputtostdout': False, 'inputdir': '/tmp/o2r/compendium/G4St5/data', 'basedir': '/tmp/o2r/compendium/', 'metafiles': True, 'ercid': 'test', 'outputdir': '/tmp/test-2'}
[o2rmeta] 20171024.100225 launching extractor
[o2rmeta] 20171024.100225 directory </tmp/test-2> will be created during extraction...
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100225 <parsers.parse_bagittxt.ParseBagitTxt object at 0x7f750da4ceb8>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100225 <parsers.parse_displayfiles.ParseDisplayFiles object at 0x7f750da4cfd0>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100225 <parsers.parse_geojson.ParseGeojson object at 0x7f750da4c8d0>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100225 <parsers.parse_rmd.ParseRmd object at 0x7f750da4c668>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100225 <parsers.parse_rdata.ParseRData object at 0x7f750da4c588>
[o2rmeta][debug: extract.metaextract @ register_parsers] 20171024.100225 <parsers.parse_yaml.ParseYaml object at 0x7f750da51518>
Traceback (most recent call last):
  File "/home/daniel/git/o2r/o2r-meta/o2rmeta.py", line 78, in <module>
    metaextract.start(dbg=argsd['debug'], i=argsd['inputdir'], o=argsd['outputdir'], s=argsd['outputtostdout'], xo=argsd['stayoffline'], e=argsd['ercid'], f=argsd['formats'], b=argsd['basedir'], m=argsd['metafiles'], xml=argsd['modexml'])
  File "/home/daniel/git/o2r/o2r-meta/extract/metaextract.py", line 334, in start
    with open(os.path.join("schema", "json", "dummy.json"), 'w', encoding='utf-8') as dummyfile:
FileNotFoundError: [Errno 2] No such file or directory: 'schema/json/dummy.json'
```

This could be a Win vs. Linux issue, the change that works for me is https://github.com/o2r-project/o2r-meta/compare/dev...nuest:bugfixing-dummy-json?expand=1

**Comment by 7048730** [comment]
yes, the fix is very simple but why did this error come up only now? we're using the dummy for months, puzzles me.
